name: awdwad
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  convert: ^3.1.2
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.8
  intl: ^0.17.0
  fl_chart: ^0.40.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  csv: ^5.0.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icon/Logo.png"
